version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: product_dev
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  product-api:
    build:
      context: ./product-api
    ports:
      - "3001:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/product_dev
    volumes:
      - ./product-api:/app
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm run start:prod"

  product-web:
    build:
      context: ./product-web
    ports:
      - "3000:80"
    depends_on:
      - product-api

volumes:
  db_data: